Vagrant.configure("2") do |config|
    # Define the first VM using CentOS
    config.vm.define "centos_vm" do |centos|
      centos.vm.box = "centos/8"  # CentOS 8
      # centos.vm.network "private_network", type: "dhcp", ip: "192.168.33.10"  # Static IP on private network
      centos.vm.network "public_network"  # Bridged to the external network
      centos.vm.provider "virtualbox" do |vb|
        vb.memory = "800"  # 600 MB of memory
      end
  
      # Shared folder
      centos.vm.synced_folder "./cent01", "/vagrant/cent01"
  
      # Provisioning section for CentOS
      centos.vm.provision "shell", inline: <<-SHELL
        # Example provisioning script for CentOS
        echo "Provisioning CentOS VM"
      SHELL
    end
  
    # ==========================================================================
  
    # Define the second VM using Ubuntu
    config.vm.define "ubuntu_vm1" do |ubuntu1|
      ubuntu1.vm.box = "ubuntu/bionic64"  # Ubuntu 18.04 LTS
      # ubuntu1.vm.network "private_network", type: "dhcp", ip: "192.168.33.11"  # Static IP on private network
      ubuntu1.vm.network "public_network"  # Bridged to the external network
      ubuntu1.vm.provider "virtualbox" do |vb|
        vb.memory = "700"  # 600 MB of memory
      end
  
      # Shared folder
      ubuntu1.vm.synced_folder "./ubu01", "/vagrant/ubu01"

      # Provisioning section for Ubuntu 1
      ubuntu1.vm.provision "shell", inline: <<-SHELL
        # Example provisioning script for Ubuntu
        echo "Provisioning Ubuntu VM"
      SHELL
    end
  end
  