---
  # Installation
  - hosts: all
    become: true
    pre_tasks:
      - name: Install apache2 (Ubuntu)
        when: ansible_distribution == "Ubuntu"
        apt:
          update_cache: true
          name: 
            - apache2
          state: latest

      - name: Install httpd (Fedora)
        when: ansible_distribution == "Fedora"
        dnf:
          update_cache: true
          name: 
            - httpd
          state: latest

  # Actual service handling
  - hosts: all
    become: true
    tasks:
      - name: Start apache2 service (Ubuntu)
        when: ansible_distribution == "Ubuntu"
        service:
          name: apache2
          state: started

      - name: Start httpd service (Fedora)
        when: ansible_distribution == "Fedora"
        service: 
          name: httpd
          state: started
          enabled: yes