#!/bin/bash

docker build -t devops-tools -f devops-tools.Dockerfile .

echo "[Complete]"
echo
echo "Run now from the directory of your choice:"
echo "$ docker run -it --rm -v \$(pwd):/app -w /app devops-tools"